### ISSUE TITLE
include image AI

### ISSUE THREAD

**Issue by se7en-x230** [slithery0/gpt-chatbot-cli#3]
Would it be possible to include an option to generate an image. I user another script that has that feature included but I would rather only use one script

**Comment by slithery0** [comment]
This package was specifically built for chat purpose, i had no plan or intention to use it for image generation. But I can built that feature if you want. Maybe wait few days, I'll update it with another more option to do so.

**Comment by rukh-debug** [comment]
I desided not to add image generation in this script, since its a chatbot.

**Comment by se7en-x230** [comment]
Understood

Thanks
